# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up 
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: go mod 
      run: go mod tidy && git diff HEAD

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up 
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
     
    - name: Test
      run: go test -coverprofile=coverage.txt -v ./...

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}